### ISSUE TITLE
This is not an issue or anything

### ISSUE THREAD

**Issue by Ashtor** [ChatTor/ChatTor#3]
i'm sending this here,since people can't send you a mail to mail2tor.. both mail2tor and sigaint is down (if they ever come back up) . I would suggest you to make an email on torbox and then put it on http://chattorci7bcgygp.onion/faq.htm .. and also make a BitMessage chan too just in case and put that too on that site

**Comment by ChatTor** [comment]
Done. Will be updating the FAQ momentarily
